### ISSUE TITLE
Invalid DNSSEC answer returned from cache

### ISSUE THREAD

**Issue by miekg** [semihalev/sdns#11]
If I start sdns and then query:

~~~
dig +cd dnssec.fail @localhost -p 1053 
dig  dnssec.fail @localhost -p 1053    
~~~

The latter returns a response while the answer is actually invalid, but has been put in the cache because of `+cd` (checking disabled).

**Comment by semihalev** [comment]
earlier I thought the checking disabled option implementation but ignored because it can make double cache and currently dnssec always on. what do you think about it? 

but there is another issue, I just see now with the dnssec.fail case, there is DS records on parent zone but no RRSIG records on zone, the condition necessary in dnssec verification.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [semihalev/sdns] Invalid DNSSEC..." ]
>earlier I thought the checking disabled option implementation but ignored because it can make double cache and currently dnssec always on. what do you think about it?

You shouldn't cache whole packets (although it obvisouly works). A change I also 
need to for CoreDNS is doing on RRsets basis instead of packet. Slightly harder 
to do and you have to be careful about putting glue and other RRs in there in .

/Miek

--
Miek Gieben

**Comment by semihalev** [comment]
opened again, I will control "checking disabled" option also.

**Comment by semihalev** [comment]
looks like done, thanks for attached me about this.
